os: osx

osx_image: xcode9.2

compiler:
  - clang
  
notifications:
  email: false
  
language: c

before_install:
  - brew update && brew bundle

install:
  - wget https://github.com/curl/curl/releases/download/curl-7_58_0/curl-7.58.0.tar.gz
  - tar -xzvf curl-7.58.0.tar.gz
  - pushd curl-7.58.0 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  - ./autogen.sh
  - ./nomacro.pl

script:
  - ./configure
  - make


sudo: false
