os: osx

language: c

compiler:
  - clang
  
notifications:
  email: false
  
osx_image: xcode9.2

before_install:
  - brew update && brew bundle 

before_script:
  - ./autogen.sh
  - ./nomacro.pl

script:
  - ./configure
  - make


sudo: flase
